filter:
    paths: [src/*]
    excluded_paths: [src/Tests/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 600
    php_code_sniffer:
        config:
            standard: "PSR2"
